name: findmydorm
description: "A location-based app that helps students find dormitories."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # ---- UI & Navigation ----
  curved_navigation_bar: ^1.0.6
  another_flutter_splash_screen: ^1.2.1
  ionicons: ^0.2.2
  flutter_typeahead: ^5.2.0

  # ---- Mapping & Location Services ----
  flutter_map: ^6.2.1
  open_street_map_search_and_pick: ^0.1.1
  latlong2: ^0.9.1
  geocoding: ^4.0.0

  # ---- Data & Backend Services (SQLite, Hive) ----
  sqflite: ^2.3.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.5.3

  # ---- Utilities & Core Logic ----
  http: ^1.2.2
  intl: ^0.19.0
  url_launcher: ^6.3.2
  snippet_coder_utils: ^1.0.15
  bcrypt: ^1.1.3
  flutter_dotenv: ^6.0.0
  collection: ^1.18.0

  # ---- Build & Asset Tools ----
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
